[package]
name = "hsm-rs"
description = "A no_std hierarchical state machine and active-object framework for Rust."
version = "0.1.1"
repository = "https://github.com/zwaggoner/hsm-rs"
readme = "README.md"
license = "MIT"
keywords = ["state-machine", "statechart", "embedded"]
categories = ["embedded", "no-std"]
edition = "2024"
rust-version = "1.91.1"

[features]
default = []
blinky-example = [
    "dep:cortex-m",
    "dep:cortex-m-rt",
    "dep:panic-halt",
    "dep:stm32f4xx-hal",
]
loom-tests = ["dep:loom"]

[dependencies]
const-str = { version = "1.1.0" }
cortex-m = { version = "0.7", optional = true }
cortex-m-rt = { version = "0.7", optional = true }
panic-halt = { version = "1", optional = true }
stm32f4xx-hal = { version = "0.23", optional = true, features = ["stm32f446"] }
loom = { version = "0.7.1", optional = true }

[[example]]
name = "sm-example"
path = "examples/sm-example.rs"

[[example]]
name = "blinky"
path = "examples/blinky.rs"
required-features = ["blinky-example"]

[[example]]
name = "basic-example"
path = "examples/basic-example.rs"
